// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AnyModel = CookieJar | Environment | Folder | GraphQlIntrospection | GrpcConnection | GrpcEvent | GrpcRequest | HttpRequest | HttpResponse | KeyValue | Plugin | Settings | SyncState | WebsocketConnection | WebsocketEvent | WebsocketRequest | Workflow | WorkflowStep | WorkflowExecution | WorkflowStepExecution | WorkflowNode | WorkflowEdge | WorkflowViewport | WorkflowNodeExecution | Workspace | WorkspaceMeta;

export type Cookie = { raw_cookie: string, domain: CookieDomain, expires: CookieExpires, path: [string, boolean], };

export type CookieDomain = { "HostOnly": string } | { "Suffix": string } | "NotPresent" | "Empty";

export type CookieExpires = { "AtUtc": string } | "SessionEnd";

export type CookieJar = { model: "cookie_jar", id: string, createdAt: string, updatedAt: string, workspaceId: string, cookies: Array<Cookie>, name: string, };

export type EdgeType = "sequential" | "conditional" | "parallel" | "loop";

export type EditorKeymap = "default" | "vim" | "vscode" | "emacs";

export type EncryptedKey = { encryptedKey: string, };

export type Environment = { model: "environment", id: string, workspaceId: string, createdAt: string, updatedAt: string, name: string, public: boolean, parentModel: string, parentId: string | null, variables: Array<EnvironmentVariable>, color: string | null, sortPriority: number, };

export type EnvironmentVariable = { enabled?: boolean, name: string, value: string, id?: string, };

export type Folder = { model: "folder", id: string, createdAt: string, updatedAt: string, workspaceId: string, folderId: string | null, authentication: Record<string, any>, authenticationType: string | null, description: string, headers: Array<HttpRequestHeader>, name: string, sortPriority: number, };

export type GraphQlIntrospection = { model: "graphql_introspection", id: string, createdAt: string, updatedAt: string, workspaceId: string, requestId: string, content: string | null, };

export type GrpcConnection = { model: "grpc_connection", id: string, createdAt: string, updatedAt: string, workspaceId: string, requestId: string, elapsed: number, error: string | null, method: string, service: string, status: number, state: GrpcConnectionState, trailers: { [key in string]?: string }, url: string, };

export type GrpcConnectionState = "initialized" | "connected" | "closed";

export type GrpcEvent = { model: "grpc_event", id: string, createdAt: string, updatedAt: string, workspaceId: string, requestId: string, connectionId: string, content: string, error: string | null, eventType: GrpcEventType, metadata: { [key in string]?: string }, status: number | null, };

export type GrpcEventType = "info" | "error" | "client_message" | "server_message" | "connection_start" | "connection_end";

export type GrpcRequest = { model: "grpc_request", id: string, createdAt: string, updatedAt: string, workspaceId: string, folderId: string | null, authenticationType: string | null, authentication: Record<string, any>, description: string, message: string, metadata: Array<HttpRequestHeader>, method: string | null, name: string, service: string | null, sortPriority: number, url: string, };

export type HttpRequest = { model: "http_request", id: string, createdAt: string, updatedAt: string, workspaceId: string, folderId: string | null, authentication: Record<string, any>, authenticationType: string | null, body: Record<string, any>, bodyType: string | null, description: string, headers: Array<HttpRequestHeader>, method: string, name: string, sortPriority: number, url: string, urlParameters: Array<HttpUrlParameter>, };

export type HttpRequestHeader = { enabled?: boolean, name: string, value: string, id?: string, };

export type HttpResponse = { model: "http_response", id: string, createdAt: string, updatedAt: string, workspaceId: string, requestId: string, bodyPath: string | null, contentLength: number | null, elapsed: number, elapsedHeaders: number, error: string | null, headers: Array<HttpResponseHeader>, remoteAddr: string | null, status: number, statusReason: string | null, state: HttpResponseState, url: string, version: string | null, };

export type HttpResponseHeader = { name: string, value: string, };

export type HttpResponseState = "initialized" | "connected" | "closed";

export type HttpUrlParameter = { enabled?: boolean, name: string, value: string, id?: string, };

export type KeyValue = { model: "key_value", id: string, createdAt: string, updatedAt: string, key: string, namespace: string, value: string, };

export type ModelChangeEvent = { "type": "upsert" } | { "type": "delete" };

export type ModelPayload = { model: AnyModel, updateSource: UpdateSource, change: ModelChangeEvent, };

export type NodeExecutionState = "pending" | "running" | "completed" | "failed" | "skipped";

export type NodeType = "trigger" | "action" | "logic";

/**
 * Node Type Definition for workflow canvas
 * Defines the schema, UI metadata, and default configuration for each node type
 */
export type NodeTypeDefinition = { category: NodeType, subtype: string, name: string, description: string, icon: string, color: string, schema: JsonValue, default_config: JsonValue, };

export type ParentAuthentication = { authentication: Record<string, any>, authenticationType: string | null, };

export type ParentHeaders = { headers: Array<HttpRequestHeader>, };

export type Plugin = { model: "plugin", id: string, createdAt: string, updatedAt: string, checkedAt: string | null, directory: string, enabled: boolean, url: string | null, };

export type PluginKeyValue = { model: "plugin_key_value", createdAt: string, updatedAt: string, pluginName: string, key: string, value: string, };

export type ProxySetting = { "type": "enabled", http: string, https: string, auth: ProxySettingAuth | null, bypass: string, disabled: boolean, } | { "type": "disabled" };

export type ProxySettingAuth = { user: string, password: string, };

export type Settings = { model: "settings", id: string, createdAt: string, updatedAt: string, appearance: string, coloredMethods: boolean, editorFont: string | null, editorFontSize: number, editorKeymap: EditorKeymap, editorSoftWrap: boolean, hideWindowControls: boolean, interfaceFont: string | null, interfaceFontSize: number, interfaceScale: number, openWorkspaceNewWindow: boolean | null, proxy: ProxySetting | null, themeDark: string, themeLight: string, updateChannel: string, hideLicenseBadge: boolean, autoupdate: boolean, autoDownloadUpdates: boolean, checkNotifications: boolean, };

export type SyncState = { model: "sync_state", id: string, workspaceId: string, createdAt: string, updatedAt: string, flushedAt: string, modelId: string, checksum: string, relPath: string, syncDir: string, };

export type UpdateSource = { "type": "background" } | { "type": "import" } | { "type": "plugin" } | { "type": "sync" } | { "type": "window", label: string, };

/**
 * Individual validation error with context
 */
export type ValidationError = { node_id: string | null, field: string | null, message: string, };

/**
 * Validation result for workflow graph validation
 */
export type ValidationResult = { valid: boolean, errors: Array<ValidationError>, };

export type WebsocketConnection = { model: "websocket_connection", id: string, createdAt: string, updatedAt: string, workspaceId: string, requestId: string, elapsed: number, error: string | null, headers: Array<HttpResponseHeader>, state: WebsocketConnectionState, status: number, url: string, };

export type WebsocketConnectionState = "initialized" | "connected" | "closing" | "closed";

export type WebsocketEvent = { model: "websocket_event", id: string, createdAt: string, updatedAt: string, workspaceId: string, requestId: string, connectionId: string, isServer: boolean, message: Array<number>, messageType: WebsocketEventType, };

export type WebsocketEventType = "binary" | "close" | "frame" | "open" | "ping" | "pong" | "text";

export type WebsocketMessageType = "text" | "binary";

export type WebsocketRequest = { model: "websocket_request", id: string, createdAt: string, updatedAt: string, workspaceId: string, folderId: string | null, authentication: Record<string, any>, authenticationType: string | null, description: string, headers: Array<HttpRequestHeader>, message: string, name: string, sortPriority: number, url: string, urlParameters: Array<HttpUrlParameter>, };

export type Workflow = { model: "workflow", id: string, createdAt: string, updatedAt: string, deletedAt: string | null, workspaceId: string, name: string, description: string | null, environmentId: string | null, sortPriority: number, };

export type WorkflowEdge = { model: "workflow_edge", id: string, createdAt: string, updatedAt: string, deletedAt: string | null, workflowId: string, sourceNodeId: string, targetNodeId: string, sourceAnchor: string, targetAnchor: string, edgeType: EdgeType, };

export type WorkflowExecution = { model: "workflow_execution", id: string, createdAt: string, updatedAt: string, deletedAt: string | null, workflowId: string, workspaceId: string, environmentId: string | null, elapsed: number | null, state: WorkflowExecutionState, error: string | null, };

export type WorkflowExecutionState = "initialized" | "running" | "completed" | "failed" | "cancelled";

export type WorkflowNode = { model: "workflow_node", id: string, createdAt: string, updatedAt: string, deletedAt: string | null, workflowId: string, nodeType: NodeType, nodeSubtype: string, positionX: number, positionY: number, width: number, height: number, name: string, description: string | null, config: JsonValue, enabled: boolean, legacyStepId: string | null, };

export type WorkflowNodeExecution = { model: "workflow_node_execution", id: string, createdAt: string, updatedAt: string, deletedAt: string | null, workflowExecutionId: string, workflowNodeId: string, elapsed: number | null, state: NodeExecutionState, error: string | null, result: JsonValue | null, loopIteration: number | null, };

export type WorkflowStep = { model: "workflow_step", id: string, createdAt: string, updatedAt: string, deletedAt: string | null, workflowId: string, requestId: string, requestModel: string, name: string, enabled: boolean, sortPriority: number, };

export type WorkflowStepExecution = { model: "workflow_step_execution", id: string, createdAt: string, updatedAt: string, deletedAt: string | null, workflowExecutionId: string, workflowStepId: string, requestId: string, responseId: string | null, responseModel: string | null, elapsed: number | null, state: WorkflowStepExecutionState, error: string | null, };

export type WorkflowStepExecutionState = "pending" | "running" | "completed" | "failed" | "skipped";

export type WorkflowViewport = { model: "workflow_viewport", id: string, createdAt: string, updatedAt: string, workflowId: string, panX: number, panY: number, zoom: number, };

export type Workspace = { model: "workspace", id: string, createdAt: string, updatedAt: string, authentication: Record<string, any>, authenticationType: string | null, description: string, headers: Array<HttpRequestHeader>, name: string, encryptionKeyChallenge: string | null, settingValidateCertificates: boolean, settingFollowRedirects: boolean, settingRequestTimeout: number, };

export type WorkspaceMeta = { model: "workspace_meta", id: string, workspaceId: string, createdAt: string, updatedAt: string, encryptionKey: EncryptedKey | null, settingSyncDir: string | null, };
