pub mod any_request;
mod batch;
mod cookie_jars;
mod environments;
mod folders;
mod graphql_introspections;
mod grpc_connections;
mod grpc_events;
mod grpc_requests;
mod http_requests;
mod http_responses;
mod key_values;
mod plugin_key_values;
mod plugins;
mod settings;
mod sync_states;
mod websocket_connections;
mod websocket_events;
mod websocket_requests;
pub mod workflow_executions;
pub mod workflow_steps;
pub mod workflows;
pub mod workflow_nodes;
pub mod workflow_edges;
pub mod workflow_viewport;
mod workspace_metas;
mod workspaces;

const MAX_HISTORY_ITEMS: usize = 20;
